version: "3"

services: 
    backend:
        build: 
            context: ./backend/
            dockerfile: dockerfile
        ports: 
            - "8000:8000"
        restart: unless-stopped
        expose: 
            - 8000
    
    front:
        build:  
            context: ./front/
            dockerfile: dockerfile
        ports: 
            - "80:80"
        volumes: 
            - /usr/src/app/nodemodules
            - ./front/:/usr/src/app
        stdin_open: true
    
        