version: "3"

services: 
    backend:
        build: 
            context: ./backand/
            dockerfile: dockerfile
        ports: 
            - "8000:8000"
        restart: always
        expose: 
            - 8000
    frontend:
      build:
        context: ./frontend/
        dockerfile: dockerfile 
      volumes:
        - /app/node_modules
        - ./:/app
      ports:
        - 80:80
      stdin_open: true

