version: "3"

services: 
    backend:
        build: 
            context: ./backend
            dockerfile: dockerfile
        ports: 
            - "8000:8000"
        restart: always
        expose: 
            - 8000
    frontend:
      build:
        dockerfile: Dockerfile 
        context: ./front
      volumes:
        - /app/node_modules
        - ./:/app
      ports:
        - "80:3000"
      stdin_open: true
    db:
        image: mariadb:10
        ports:
          - 1994:3306
        env_file: .env
        environment:
          TZ: Asia/Seoul
        volumes:
          - ./db/data:/var/lib/mysql
          - ./db/config:/etc/mysql/conf.d
        restart: always
