version: "3"

services: 
    backend:
        build: 
            context: ./backend/
            dockerfile: dockerfile
        ports: 
            - "8000:8000"
        restart: always
        expose: 
            - 8000
    front:
        build:  
            context: ./front/
            dockerfile: dockerfile
        ports: 
            - "80:80"
        volumes: 
            - /usr/src/app/nodemodules
            - ./front/:/usr/src/app
        stdin_open: true
        restart: always
    db:
        image: mariadb:10
        ports:
          - 3306:3306
          environment:
          - MYSQL_ROOT_PASSWORD: chltjdgus123!
          - MYSQL_DATABASE: myblog
          - MYSQL_USER: cshcmi
          - MYSQL_PASSWORD: chltjdgsu123!
        volumes:
          - ./db/data:/var/lib/mysql
          - ./db/config:/etc/mysql/conf.d
        environment:
          TZ: Asia/Seoul
        restart: always
