version: "3"

services: 
    jenkins:
      build: .
      image: jenkins/jenkins
      restart: always
      container_name: jenkins
      user: root
      ports:
        - 8080:8080
      volumes:
        - ./jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        TZ: "Asia/Seoul"
    backend:
        build: 
            context: ./backend/
            dockerfile: dockerfile
        ports: 
            - "8000:8000"
        restart: always
        expose: 
            - 8000
    frontend:
      build:
        context: ./front/
        dockerfile: dockerfile 
      volumes:
        - /app/node_modules
        - ./:/app
      ports:
        - 80:80
      stdin_open: true
    db:
        image: mariadb:10
        ports:
          - 1994:3306
        env_file: .env
        environment:
          TZ: Asia/Seoul
        volumes:
          - ./db/data:/var/lib/mysql
          - ./db/config:/etc/mysql/conf.d
        restart: always
