version: "3"

services: 
    backend:
        build: 
            context: ./backend/
            dockerfile: dockerfile
        ports: 
            - "8000:8000"
        restart: always
        expose: 
            - 8000
    
    front:
        build:  
            context: ./front/
            dockerfile: dockerfile
        ports: 
            - "80:80"
        volumes: 
            - /usr/src/app/nodemodules
            - ./front/:/usr/src/app
        stdin_open: true
        restart: always
    
    db:
        image: mysql/mysql-server:8.0.25-1.2.3-server
        restart: always
        command: --lower_case_table_names=1
        container_name: mysql-test
        ports:
          - "3306:3306"
        environment:
          - MYSQL_DATABASE=reactgo
          - MYSQL_ROOT_PASSWORD=chltjdgus123!
          - TZ=Asia/Seoul
    
        command:
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
        volumes:
          - ./mysql:/var/lib/mysql