// Code generated by entc, DO NOT EDIT.

package cipher

const (
	// Label holds the string label denoting the cipher type in the database.
	Label = "cipher"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDefault holds the string denoting the default field in the database.
	FieldDefault = "default"
	// Table holds the table name of the cipher in the database.
	Table = "ciphers"
)

// Columns holds all SQL columns for cipher fields.
var Columns = []string{
	FieldID,
	FieldDefault,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
