// Code generated by entc, DO NOT EDIT.

package cipher

import (
	"entgo.io/ent/dialect/sql"
	"github.com/backand/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Default applies equality check predicate on the "default" field. It's identical to DefaultEQ.
func Default(v []byte) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDefault), v))
	})
}

// DefaultEQ applies the EQ predicate on the "default" field.
func DefaultEQ(v []byte) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDefault), v))
	})
}

// DefaultNEQ applies the NEQ predicate on the "default" field.
func DefaultNEQ(v []byte) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDefault), v))
	})
}

// DefaultIn applies the In predicate on the "default" field.
func DefaultIn(vs ...[]byte) predicate.Cipher {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cipher(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDefault), v...))
	})
}

// DefaultNotIn applies the NotIn predicate on the "default" field.
func DefaultNotIn(vs ...[]byte) predicate.Cipher {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cipher(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDefault), v...))
	})
}

// DefaultGT applies the GT predicate on the "default" field.
func DefaultGT(v []byte) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDefault), v))
	})
}

// DefaultGTE applies the GTE predicate on the "default" field.
func DefaultGTE(v []byte) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDefault), v))
	})
}

// DefaultLT applies the LT predicate on the "default" field.
func DefaultLT(v []byte) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDefault), v))
	})
}

// DefaultLTE applies the LTE predicate on the "default" field.
func DefaultLTE(v []byte) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDefault), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Cipher) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Cipher) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Cipher) predicate.Cipher {
	return predicate.Cipher(func(s *sql.Selector) {
		p(s.Not())
	})
}
