FROM golang:latest

RUN apt update && apt upgrade -y && \
    apt install -y bash git openssh-server

WORKDIR /app

RUN mkdir -p /app/github.com

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build

CMD ["./backand"]