FROM node:latest as builder

WORKDIR '/usr/src/app'

COPY package.json ./

RUN npm install

COPY ./ ./

RUN npm run build

FROM nginx

RUN mkdir /app

WORKDIR /app

RUN mkdir ./build

COPY --from=builder /usr/src/app/build ./build

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]