FROM node:latest as builder
WORKDIR /app
COPY ./package*.json ./
RUN npm install
RUN yarn install
COPY . .
RUN npm run build


FROM nginx
EXPOSE 80
COPY ./defalut.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build  /usr/share/nginx/html
