FROM node:12.16.2 as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install -g n
RUN npm install 

COPY . /usr/src/app
RUN npm run build

FROM nginx:latest

RUN mkdir /app

WORKDIR /app

RUN mkdir ./build

RUN rm /etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d

COPY --from=builder /usr/src/app/build ./build

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]